/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Starbase({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Starbase/interior.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RoboArmAture" position={[-5.5, 2.95, -8.72]} scale={2.79}>
          <primitive object={nodes.RoboArmRoot} />
          <skinnedMesh name="RoboArm00_1" geometry={nodes.RoboArm00_1.geometry} material={materials.VCol} skeleton={nodes.RoboArm00_1.skeleton} />
        </group>
        <group name="BoneVis00004" position={[1.49, 0, 2.45]} scale={2.79} />
        <group name="BoneVis00003" position={[1.49, 0, 2.45]} scale={2.79} />
        <group name="BoneVis00002" position={[1.49, 0, 2.45]} scale={2.79} />
        <group name="BoneVis00001" position={[1.49, 0, 2.45]} scale={2.79} />
        <group name="BoneVis00" position={[1.49, 0, 2.45]} scale={2.79} />
        <group name="Cube002" position={[-12.55, 6.26, -0.18]} rotation={[0, -0.03, 0]} scale={[0.98, 1, 0.48]}>
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Gates.003']} />
          <mesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['Walls.002']} />
        </group>
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Gates.004']} position={[-14.37, 3.01, -0.3]} rotation={[0, -0.03, 0]} scale={[0.98, 1, 0.48]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Gates.004']} position={[-10.86, 3.01, -0.23]} rotation={[0, -0.03, 0]} scale={[-0.98, 1, 0.48]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Gates.005']} position={[-16.76, 3.04, -23.72]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Gates.005']} position={[-16.76, 3.04, -20.14]} rotation={[0, -Math.PI / 2, 0]} scale={[-1, 1, 1]} />
        <group name="Cube001" position={[-16.82, 6.26, -21.85]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Gates.005']} />
          <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials['Walls.003']} />
        </group>
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Walls.004']} position={[-25.11, 0.16, -4.53]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]} />
        <group name="Plane006" position={[-25.11, 1.81, -8.59]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane008_1" geometry={nodes.Plane008_1.geometry} material={materials['SmallLamps.001']} />
          <mesh name="Plane008_2" geometry={nodes.Plane008_2.geometry} material={materials['SmallLampsEmission.001']} />
        </group>
        <group name="Plane007" position={[-25.1, 6.09, -8]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane009_1" geometry={nodes.Plane009_1.geometry} material={materials['SmallLamps.001']} />
          <mesh name="Plane009_2" geometry={nodes.Plane009_2.geometry} material={materials['SmallLampsEmission.001']} />
        </group>
        <group name="Plane008" position={[-25.11, 6.09, -1.04]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials['SmallLamps.001']} />
          <mesh name="Plane010_2" geometry={nodes.Plane010_2.geometry} material={materials['SmallLampsEmission.001']} />
        </group>
        <group name="Plane009" position={[-25.11, 1.81, -0.45]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane011_1" geometry={nodes.Plane011_1.geometry} material={materials['SmallLamps.001']} />
          <mesh name="Plane011_2" geometry={nodes.Plane011_2.geometry} material={materials['SmallLampsEmission.001']} />
        </group>
        <group name="Plane010" position={[-25.04, 5.66, -4.38]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane012_1" geometry={nodes.Plane012_1.geometry} material={materials['SmallLamps.001']} />
          <mesh name="Plane012_2" geometry={nodes.Plane012_2.geometry} material={materials['SmallLampsEmission.001']} />
        </group>
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Cover.001']} position={[-25.13, 0.52, -7.53]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Cover.001']} position={[-25.13, 0.52, -1.36]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]} />
        <mesh name="Workbench00" geometry={nodes.Workbench00.geometry} material={materials.VCol} position={[-4.1, 0, -8.72]} scale={2.79} />
        <mesh name="Couch00" geometry={nodes.Couch00.geometry} material={materials['VCol.001']} position={[-23.3, -0.09, -1.89]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-2.33, 2.33, 2.33]} />
        <mesh name="ScreenWall00" geometry={nodes.ScreenWall00.geometry} material={materials['VCol.002']} position={[-21.3, 3.69, -8.69]} scale={2.99} />
        <mesh name="Shelf00" geometry={nodes.Shelf00.geometry} material={materials['VCol.003']} position={[-1.19, 0, -3.33]} scale={3.09} />
        <mesh name="ToolCrate07" geometry={nodes.ToolCrate07.geometry} material={materials['VCol.004']} position={[-8.89, 1.89, -1.71]} rotation={[-Math.PI / 2, 0, 0.31]} scale={3.26} />
        <mesh name="ToolCrate06" geometry={nodes.ToolCrate06.geometry} material={materials['VCol.004']} position={[-9.4, 0.62, -1.21]} rotation={[0, -0.16, 0]} scale={3.26} />
        <mesh name="ToolCrate06001" geometry={nodes.ToolCrate06001.geometry} material={materials['VCol.005']} position={[-8.62, 0.62, -2.42]} rotation={[0, -0.52, 0]} scale={3.26} />
        <mesh name="ToolCrate11" geometry={nodes.ToolCrate11.geometry} material={materials['VCol.006']} position={[-15.85, 0.65, -7.77]} rotation={[0, 0.54, 0]} scale={3.18} />
        <mesh name="ScrewDriver00" geometry={nodes.ScrewDriver00.geometry} material={materials['VCol.007']} position={[-0.97, 0.18, -4.22]} scale={3.11} />
        <mesh name="Hammer00" geometry={nodes.Hammer00.geometry} material={materials['VCol.007']} position={[-1.33, 1.58, -3.02]} scale={3.11} />
        <group name="Cube176" position={[-12.63, 6.23, -4.59]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
          <mesh name="Cube205" geometry={nodes.Cube205.geometry} material={materials.Lamp} />
          <mesh name="Cube205_1" geometry={nodes.Cube205_1.geometry} material={materials.LampEmission} />
        </group>
        <mesh name="Plane285" geometry={nodes.Plane285.geometry} material={materials.Walls} position={[-25.26, 0.16, -21.93]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]} />
        <group name="Plane284" position={[-25.26, 1.81, -26]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane321" geometry={nodes.Plane321.geometry} material={materials.SmallLamps} />
          <mesh name="Plane321_1" geometry={nodes.Plane321_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <group name="Plane283" position={[-25.26, 6.09, -25.41]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane320" geometry={nodes.Plane320.geometry} material={materials.SmallLamps} />
          <mesh name="Plane320_1" geometry={nodes.Plane320_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <group name="Plane282" position={[-25.26, 6.09, -18.45]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane319" geometry={nodes.Plane319.geometry} material={materials.SmallLamps} />
          <mesh name="Plane319_1" geometry={nodes.Plane319_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <group name="Plane281" position={[-25.26, 1.81, -17.86]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane318" geometry={nodes.Plane318.geometry} material={materials.SmallLamps} />
          <mesh name="Plane318_1" geometry={nodes.Plane318_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <group name="Plane280" position={[-25.19, 5.66, -21.78]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]}>
          <mesh name="Plane317" geometry={nodes.Plane317.geometry} material={materials.SmallLamps} />
          <mesh name="Plane317_1" geometry={nodes.Plane317_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <mesh name="Plane279" geometry={nodes.Plane279.geometry} material={materials.Cover} position={[-25.29, 0.52, -24.94]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]} />
        <mesh name="Plane278" geometry={nodes.Plane278.geometry} material={materials.Cover} position={[-25.29, 0.52, -18.76]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]} />
        <mesh name="Plane277" geometry={nodes.Plane277.geometry} material={materials.Clock} position={[-25.26, 0.16, -21.93]} rotation={[0, Math.PI / 2, 0]} scale={[1.02, 1, 1]} />
        <group name="Plane276" position={[-21.27, 2.8, -26.91]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Plane313" geometry={nodes.Plane313.geometry} material={materials.Doors} />
          <mesh name="Plane313_1" geometry={nodes.Plane313_1.geometry} material={materials.DoorsEmition} />
        </group>
        <group name="Plane275" position={[-21.27, 2.8, -17.35]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Plane312" geometry={nodes.Plane312.geometry} material={materials.Doors} />
          <mesh name="Plane312_1" geometry={nodes.Plane312_1.geometry} material={materials.DoorsEmition} />
        </group>
        <group name="Plane274" position={[-18.49, 0.1, -21.93]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Plane311" geometry={nodes.Plane311.geometry} material={materials.Walls} />
          <mesh name="Plane311_1" geometry={nodes.Plane311_1.geometry} material={materials.Floors} />
        </group>
        <group name="Cube165" position={[-21.98, 3.79, -26.62]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Cube191" geometry={nodes.Cube191.geometry} material={materials.DoorsLock} />
          <mesh name="Cube191_1" geometry={nodes.Cube191_1.geometry} material={materials.DoorsLockHologram} />
        </group>
        <mesh name="Cube164" geometry={nodes.Cube164.geometry} material={materials.Doors} position={[-19.8, 0.38, -26.85]} rotation={[0, Math.PI / 2, 0]} />
        <group name="Cube163" position={[-21.98, 3.79, -17.64]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Cube189" geometry={nodes.Cube189.geometry} material={materials.DoorsLock} />
          <mesh name="Cube189_1" geometry={nodes.Cube189_1.geometry} material={materials.DoorsLockHologram} />
        </group>
        <mesh name="Cube162" geometry={nodes.Cube162.geometry} material={materials.Doors} position={[-19.8, 0.38, -17.41]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane264" geometry={nodes.Plane264.geometry} material={materials.Clock} position={[-29.73, 0.16, -9.24]} />
        <mesh name="Plane263" geometry={nodes.Plane263.geometry} material={materials.Cover} position={[-32.83, 0.52, -9.27]} />
        <mesh name="Plane262" geometry={nodes.Plane262.geometry} material={materials.Cover} position={[-26.8, 0.52, -9.27]} />
        <group name="Plane261" position={[-29.74, 5.67, -9.18]}>
          <mesh name="Plane298" geometry={nodes.Plane298.geometry} material={materials.SmallLamps} />
          <mesh name="Plane298_1" geometry={nodes.Plane298_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <group name="Plane260" position={[-33.71, 1.81, -9.24]}>
          <mesh name="Plane297" geometry={nodes.Plane297.geometry} material={materials.SmallLamps} />
          <mesh name="Plane297_1" geometry={nodes.Plane297_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <group name="Plane259" position={[-33.14, 6.09, -9.24]}>
          <mesh name="Plane296" geometry={nodes.Plane296.geometry} material={materials.SmallLamps} />
          <mesh name="Plane296_1" geometry={nodes.Plane296_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <group name="Plane258" position={[-26.33, 6.09, -9.24]}>
          <mesh name="Plane295" geometry={nodes.Plane295.geometry} material={materials.SmallLamps} />
          <mesh name="Plane295_1" geometry={nodes.Plane295_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <group name="Plane257" position={[-25.75, 1.81, -9.24]}>
          <mesh name="Plane294" geometry={nodes.Plane294.geometry} material={materials.SmallLamps} />
          <mesh name="Plane294_1" geometry={nodes.Plane294_1.geometry} material={materials.SmallLampsEmission} />
        </group>
        <mesh name="Plane256" geometry={nodes.Plane256.geometry} material={materials.Walls} position={[-29.73, 0.16, -9.24]} />
        <group name="Sphere111" position={[-33.68, 3.76, -19.74]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, 0.55]}>
          <mesh name="Sphere130" geometry={nodes.Sphere130.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere130_1" geometry={nodes.Sphere130_1.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere110" position={[-33.68, 1.85, -19.74]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, 0.55]}>
          <mesh name="Sphere129" geometry={nodes.Sphere129.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere129_1" geometry={nodes.Sphere129_1.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere109" position={[-33.68, 1.85, -22.6]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, 0.55]}>
          <mesh name="Sphere128" geometry={nodes.Sphere128.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere128_1" geometry={nodes.Sphere128_1.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere108" position={[-33.68, 2.85, -21.22]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, 0.55]}>
          <mesh name="Sphere127" geometry={nodes.Sphere127.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere127_1" geometry={nodes.Sphere127_1.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere107" position={[-33.68, 3.76, -22.6]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, 0.55]}>
          <mesh name="Sphere126" geometry={nodes.Sphere126.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere126_1" geometry={nodes.Sphere126_1.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere106" position={[-33.68, 4.7, -21.22]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, 0.55]}>
          <mesh name="Sphere125" geometry={nodes.Sphere125.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere125_1" geometry={nodes.Sphere125_1.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <mesh name="Plane240" geometry={nodes.Plane240.geometry} material={materials.Cover} position={[-33.13, 0.24, -23.44]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Plane239" geometry={nodes.Plane239.geometry} material={materials.Cover} position={[-33.13, 0.24, -21.63]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Plane238" geometry={nodes.Plane238.geometry} material={materials.Cover} position={[-33.13, 0.24, -20.09]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Plane237" geometry={nodes.Plane237.geometry} material={materials.Cover} position={[-33.13, 0.24, -18.65]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Plane236" geometry={nodes.Plane236.geometry} material={materials.Cover} position={[-26.92, 0.24, -25.03]} rotation={[0, 1.57, 0]} />
        <mesh name="Plane235" geometry={nodes.Plane235.geometry} material={materials.Cover} position={[-28.73, 0.24, -25.03]} rotation={[0, 1.57, 0]} />
        <mesh name="Plane234" geometry={nodes.Plane234.geometry} material={materials.Cover} position={[-30.27, 0.24, -25.03]} rotation={[0, 1.57, 0]} />
        <mesh name="Plane233" geometry={nodes.Plane233.geometry} material={materials.Cover} position={[-31.71, 0.24, -25.03]} rotation={[0, 1.57, 0]} />
        <group name="Plane232" position={[-29.78, 0.13, -21.69]}>
          <mesh name="Plane269" geometry={nodes.Plane269.geometry} material={materials.Walls} />
          <mesh name="Plane269_1" geometry={nodes.Plane269_1.geometry} material={materials.Floors} />
        </group>
        <group name="Cube153" position={[-29.54, 6.24, -21.14]} rotation={[0, 0, -Math.PI]}>
          <mesh name="Cube179" geometry={nodes.Cube179.geometry} material={materials.Lamp} />
          <mesh name="Cube179_1" geometry={nodes.Cube179_1.geometry} material={materials.LampEmission} />
        </group>
        <group name="Cube152" position={[-26.39, 2.66, -25.84]} rotation={[0, -Math.PI / 2, 0]} scale={[0.4, 0.1, 0.1]}>
          <mesh name="Cube178" geometry={nodes.Cube178.geometry} material={materials.ControlScreen} />
          <mesh name="Cube178_1" geometry={nodes.Cube178_1.geometry} material={materials.ControlScreenEmission} />
        </group>
        <mesh name="Cube151" geometry={nodes.Cube151.geometry} material={materials.FireExtinuisher} position={[-33.8, 4.55, -19.84]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, 0.03]} />
        <mesh name="Cube150" geometry={nodes.Cube150.geometry} material={materials.FireExtinuisher} position={[-33.8, 2.64, -19.84]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, 0.03]} />
        <mesh name="Cube149" geometry={nodes.Cube149.geometry} material={materials.FireExtinuisher} position={[-33.8, 2.64, -22.7]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, 0.03]} />
        <mesh name="Cube148" geometry={nodes.Cube148.geometry} material={materials.FireExtinuisher} position={[-33.8, 3.64, -21.32]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, 0.03]} />
        <mesh name="Cube147" geometry={nodes.Cube147.geometry} material={materials.FireExtinuisher} position={[-33.8, 4.55, -22.7]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, 0.03]} />
        <mesh name="Cube146" geometry={nodes.Cube146.geometry} material={materials.FireExtinuisher} position={[-33.8, 5.48, -21.32]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, 0.03]} />
        <group name="Cross_Joint023" position={[-33.31, 0.25, -20.29]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh name="Cross_Joint029" geometry={nodes.Cross_Joint029.geometry} material={materials.PipesRed} />
          <mesh name="Cross_Joint029_1" geometry={nodes.Cross_Joint029_1.geometry} material={materials.PipesBlue} />
          <mesh name="Cross_Joint029_2" geometry={nodes.Cross_Joint029_2.geometry} material={materials.PipesBrown} />
        </group>
        <group name="Cross_Joint022" position={[-30.07, 0.25, -25.21]} rotation={[0, 1.57, 0]}>
          <mesh name="Cross_Joint028" geometry={nodes.Cross_Joint028.geometry} material={materials.PipesRed} />
          <mesh name="Cross_Joint028_1" geometry={nodes.Cross_Joint028_1.geometry} material={materials.PipesBlue} />
          <mesh name="Cross_Joint028_2" geometry={nodes.Cross_Joint028_2.geometry} material={materials.PipesBrown} />
        </group>
        <group name="Plane220" position={[-34.34, 2.8, -13.58]}>
          <mesh name="Plane257_1" geometry={nodes.Plane257_1.geometry} material={materials.Doors} />
          <mesh name="Plane257_2" geometry={nodes.Plane257_2.geometry} material={materials.DoorsEmition} />
        </group>
        <group name="Plane219" position={[-29.76, 0.1, -10.8]}>
          <mesh name="Plane256_1" geometry={nodes.Plane256_1.geometry} material={materials.Walls} />
          <mesh name="Plane256_2" geometry={nodes.Plane256_2.geometry} material={materials.Floors} />
        </group>
        <mesh name="Cube130" geometry={nodes.Cube130.geometry} material={materials.Doors} position={[-34.28, 0.38, -12.11]} />
        <group name="Cube129" position={[-34.05, 3.79, -14.29]}>
          <mesh name="Cube155" geometry={nodes.Cube155.geometry} material={materials.DoorsLock} />
          <mesh name="Cube155_1" geometry={nodes.Cube155_1.geometry} material={materials.DoorsLockHologram} />
        </group>
        <mesh name="Cube128" geometry={nodes.Cube128.geometry} material={materials['Wall pilows']} position={[-26.23, 1.76, -13.37]} />
        <mesh name="Cube127" geometry={nodes.Cube127.geometry} material={materials['Wall pilows']} position={[-26.23, 1.76, -15.71]} />
        <mesh name="Cube126" geometry={nodes.Cube126.geometry} material={materials['Wall pilows']} position={[-26.23, 1.76, -11.11]} />
        <mesh name="Cube125" geometry={nodes.Cube125.geometry} material={materials['Wall pilows']} position={[-33.23, 1.76, -15.92]} />
        <mesh name="Cube124" geometry={nodes.Cube124.geometry} material={materials['Wall pilows']} position={[-33.23, 1.76, -11]} />
        <group name="Cross_Joint017" position={[-30.07, 0.25, -1.02]} rotation={[0, 1.57, 0]} scale={[-1, 1, 1]}>
          <mesh name="Cross_Joint023_1" geometry={nodes.Cross_Joint023_1.geometry} material={materials.PipesRed} />
          <mesh name="Cross_Joint023_2" geometry={nodes.Cross_Joint023_2.geometry} material={materials.PipesBlue} />
          <mesh name="Cross_Joint023_3" geometry={nodes.Cross_Joint023_3.geometry} material={materials.PipesBrown} />
        </group>
        <group name="Cross_Joint016" position={[-33.31, 0.25, -5.95]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, -1]}>
          <mesh name="Cross_Joint022_1" geometry={nodes.Cross_Joint022_1.geometry} material={materials.PipesRed} />
          <mesh name="Cross_Joint022_2" geometry={nodes.Cross_Joint022_2.geometry} material={materials.PipesBlue} />
          <mesh name="Cross_Joint022_3" geometry={nodes.Cross_Joint022_3.geometry} material={materials.PipesBrown} />
        </group>
        <mesh name="Cube115" geometry={nodes.Cube115.geometry} material={materials.FireExtinuisher} position={[-33.8, 5.48, -4.92]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, -0.03]} />
        <mesh name="Cube114" geometry={nodes.Cube114.geometry} material={materials.FireExtinuisher} position={[-33.8, 4.55, -3.54]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, -0.03]} />
        <mesh name="Cube113" geometry={nodes.Cube113.geometry} material={materials.FireExtinuisher} position={[-33.8, 3.64, -4.92]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, -0.03]} />
        <mesh name="Cube112" geometry={nodes.Cube112.geometry} material={materials.FireExtinuisher} position={[-33.8, 2.64, -3.54]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, -0.03]} />
        <mesh name="Cube111" geometry={nodes.Cube111.geometry} material={materials.FireExtinuisher} position={[-33.8, 2.64, -6.4]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, -0.03]} />
        <mesh name="Cube110" geometry={nodes.Cube110.geometry} material={materials.FireExtinuisher} position={[-33.8, 4.55, -6.4]} rotation={[0.01, 0, -Math.PI / 2]} scale={[0.03, 0.08, -0.03]} />
        <group name="Cube109" position={[-26.39, 2.66, -0.39]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.4, 0.1, 0.1]}>
          <mesh name="Cube135" geometry={nodes.Cube135.geometry} material={materials.ControlScreen} />
          <mesh name="Cube135_1" geometry={nodes.Cube135_1.geometry} material={materials.ControlScreenEmission} />
        </group>
        <group name="Cube108" position={[-29.54, 6.24, -5.1]} rotation={[0, 0, -Math.PI]} scale={[1, 1, -1]}>
          <mesh name="Cube134" geometry={nodes.Cube134.geometry} material={materials.Lamp} />
          <mesh name="Cube134_1" geometry={nodes.Cube134_1.geometry} material={materials.LampEmission} />
        </group>
        <group name="Plane208" position={[-29.78, 0.13, -4.55]} scale={[1, 1, -1]}>
          <mesh name="Plane245" geometry={nodes.Plane245.geometry} material={materials.Walls} />
          <mesh name="Plane245_1" geometry={nodes.Plane245_1.geometry} material={materials.Floors} />
        </group>
        <mesh name="Plane207" geometry={nodes.Plane207.geometry} material={materials.Cover} position={[-31.71, 0.24, -1.2]} rotation={[0, 1.57, 0]} scale={[-1, 1, 1]} />
        <mesh name="Plane206" geometry={nodes.Plane206.geometry} material={materials.Cover} position={[-30.27, 0.24, -1.2]} rotation={[0, 1.57, 0]} scale={[-1, 1, 1]} />
        <mesh name="Plane205" geometry={nodes.Plane205.geometry} material={materials.Cover} position={[-28.73, 0.24, -1.2]} rotation={[0, 1.57, 0]} scale={[-1, 1, 1]} />
        <mesh name="Plane204" geometry={nodes.Plane204.geometry} material={materials.Cover} position={[-26.92, 0.24, -1.2]} rotation={[0, 1.57, 0]} scale={[-1, 1, 1]} />
        <mesh name="Plane203" geometry={nodes.Plane203.geometry} material={materials.Cover} position={[-33.13, 0.24, -7.59]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, -1]} />
        <mesh name="Plane202" geometry={nodes.Plane202.geometry} material={materials.Cover} position={[-33.13, 0.24, -6.15]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, -1]} />
        <mesh name="Plane201" geometry={nodes.Plane201.geometry} material={materials.Cover} position={[-33.13, 0.24, -4.61]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, -1]} />
        <mesh name="Plane200" geometry={nodes.Plane200.geometry} material={materials.Cover} position={[-33.13, 0.24, -2.79]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, -1]} />
        <group name="Sphere093" position={[-33.68, 4.7, -5.02]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, -0.55]}>
          <mesh name="Sphere112" geometry={nodes.Sphere112.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere112_1" geometry={nodes.Sphere112_1.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere092" position={[-33.68, 3.76, -3.64]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, -0.55]}>
          <mesh name="Sphere111_1" geometry={nodes.Sphere111_1.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere111_2" geometry={nodes.Sphere111_2.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere091" position={[-33.68, 2.85, -5.02]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, -0.55]}>
          <mesh name="Sphere110_1" geometry={nodes.Sphere110_1.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere110_2" geometry={nodes.Sphere110_2.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere090" position={[-33.68, 1.85, -3.64]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, -0.55]}>
          <mesh name="Sphere109_1" geometry={nodes.Sphere109_1.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere109_2" geometry={nodes.Sphere109_2.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere089" position={[-33.68, 1.85, -6.5]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, -0.55]}>
          <mesh name="Sphere108_1" geometry={nodes.Sphere108_1.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere108_2" geometry={nodes.Sphere108_2.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <group name="Sphere088" position={[-33.68, 3.76, -6.5]} rotation={[-0.7, 0, -Math.PI / 2]} scale={[0.55, 0.14, -0.55]}>
          <mesh name="Sphere107_1" geometry={nodes.Sphere107_1.geometry} material={materials.FireExtinuisher} />
          <mesh name="Sphere107_2" geometry={nodes.Sphere107_2.geometry} material={materials.FireExtinguisherEmission} />
        </group>
        <mesh name="Plane197" geometry={nodes.Plane197.geometry} material={materials.Gates} position={[-0.14, 3.04, -2.69]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane196" geometry={nodes.Plane196.geometry} material={materials.Gates} position={[-0.14, 3.04, -6.28]} rotation={[0, Math.PI / 2, 0]} scale={[-1, 1, 1]} />
        <group name="Cube106" position={[-0.07, 6.26, -4.56]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Cube132" geometry={nodes.Cube132.geometry} material={materials.Gates} />
          <mesh name="Cube132_1" geometry={nodes.Cube132_1.geometry} material={materials.Walls} />
        </group>
        <group name="Plane193" position={[-4.58, 2.8, 0.01]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Plane230" geometry={nodes.Plane230.geometry} material={materials.Doors} />
          <mesh name="Plane230_1" geometry={nodes.Plane230_1.geometry} material={materials.DoorsEmition} />
        </group>
        <group name="Plane192" position={[-1.81, 0.1, -4.56]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Plane229" geometry={nodes.Plane229.geometry} material={materials.Walls} />
          <mesh name="Plane229_1" geometry={nodes.Plane229_1.geometry} material={materials.Floors} />
        </group>
        <mesh name="Cube104" geometry={nodes.Cube104.geometry} material={materials.Doors} position={[-3.11, 0.38, -0.05]} rotation={[0, Math.PI / 2, 0]} />
        <group name="Cube103" position={[-5.3, 3.79, -0.28]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Cube129_1" geometry={nodes.Cube129_1.geometry} material={materials.DoorsLock} />
          <mesh name="Cube129_2" geometry={nodes.Cube129_2.geometry} material={materials.DoorsLockHologram} />
        </group>
        <mesh name="Cube099" geometry={nodes.Cube099.geometry} material={materials['Wall pilows']} position={[-6.93, 1.76, -1.1]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube098" geometry={nodes.Cube098.geometry} material={materials['Wall pilows']} position={[-2, 1.76, -1.1]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube097" geometry={nodes.Cube097.geometry} material={materials['Wall pilows']} position={[-18.5, 1.76, -1.1]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube096" geometry={nodes.Cube096.geometry} material={materials['Wall pilows']} position={[-23.43, 1.76, -1.1]} rotation={[0, Math.PI / 2, 0]} />
        <group name="Cube092" position={[-21.8, 3.79, -0.28]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Cube118" geometry={nodes.Cube118.geometry} material={materials.DoorsLock} />
          <mesh name="Cube118_1" geometry={nodes.Cube118_1.geometry} material={materials.DoorsLockHologram} />
        </group>
        <mesh name="Cube091" geometry={nodes.Cube091.geometry} material={materials.Doors} position={[-19.61, 0.38, -0.05]} rotation={[0, Math.PI / 2, 0]} />
        <group name="Plane191" position={[-18.31, 0.1, -4.56]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Plane228" geometry={nodes.Plane228.geometry} material={materials.Walls} />
          <mesh name="Plane228_1" geometry={nodes.Plane228_1.geometry} material={materials.Floors} />
        </group>
        <group name="Plane190" position={[-21.08, 2.8, 0.01]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Plane227" geometry={nodes.Plane227.geometry} material={materials.Doors} />
          <mesh name="Plane227_1" geometry={nodes.Plane227_1.geometry} material={materials.DoorsEmition} />
        </group>
        <group name="Plane015" position={[-12.66, 0.12, -4.66]}>
          <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={materials.Walls} />
          <mesh name="Plane042_1" geometry={nodes.Plane042_1.geometry} material={materials.Floors} />
        </group>
        <group name="Cube105" position={[-12.59, 6.26, -9.47]}>
          <mesh name="Cube131" geometry={nodes.Cube131.geometry} material={materials.Gates} />
          <mesh name="Cube131_1" geometry={nodes.Cube131_1.geometry} material={materials.Walls} />
        </group>
        <mesh name="Plane194" geometry={nodes.Plane194.geometry} material={materials.Gates} position={[-10.88, 3.04, -9.53]} scale={[-1, 1, 1]} />
        <mesh name="Plane195" geometry={nodes.Plane195.geometry} material={materials.Gates} position={[-14.46, 3.04, -9.53]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Starbase/interior.glb')
