/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lantern/Lantern.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]} position={[-40, 0, 0]}>
        <mesh geometry={nodes.LanternPole_Body.geometry} material={materials.LanternPost_Mat} position={[-3.82, 13.02, 0]} />
        <mesh geometry={nodes.LanternPole_Chain.geometry} material={materials.LanternPost_Mat} position={[-9.58, 21.04, 0]} />
        <mesh geometry={nodes.LanternPole_Lantern.geometry} material={materials.LanternPost_Mat} position={[-9.58, 18.01, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Lantern.gltf')
